# Generated by Django 2.1.2 on 2018-12-05 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(help_text='Unique ID of news entry', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='News title', max_length=100)),
                ('contents', models.CharField(help_text='News message', max_length=500)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
