# Generated by Django 2.1 on 2018-09-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('request_for_others', models.BooleanField(default=False)),
                ('need_food', models.BooleanField(default=False)),
                ('need_medicine', models.BooleanField(default=False)),
                ('need_rescue', models.BooleanField(default=False)),
            ],
        ),
    ]
