# Generated by Django 2.1.1 on 2018-09-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20180912_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='lat',
            field=models.CharField(help_text='Latitude', max_length=20),
        ),
        migrations.AlterField(
            model_name='requests',
            name='lng',
            field=models.CharField(help_text='Longitude', max_length=20),
        ),
        migrations.AlterField(
            model_name='requests',
            name='location',
            field=models.CharField(help_text='Location name', max_length=60),
        ),
        migrations.AlterField(
            model_name='requests',
            name='name',
            field=models.CharField(help_text='Name of requestee', max_length=50),
        ),
        migrations.AlterField(
            model_name='requests',
            name='phone',
            field=models.CharField(help_text='Phone of requestee', max_length=20),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_for_others',
            field=models.BooleanField(default=False, help_text='Whether this request is not made for yourself'),
        ),
    ]
