# Generated by Django 2.1.1 on 2018-09-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_auto_20180912_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(default='', help_text='Status of request', max_length=15),
            preserve_default=False,
        ),
    ]
