# Generated by Django 2.1.1 on 2018-09-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_requests_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='request_for_others',
        ),
        migrations.AddField(
            model_name='requests',
            name='number_of_people_with_you',
            field=models.IntegerField(default=0, help_text='The number of people stranded with you'),
        ),
    ]
