# Generated by Django 2.1.1 on 2018-09-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0005_auto_20180914_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='request_for_others',
            field=models.BooleanField(default=False, help_text='Whether this request is not made for yourself'),
        ),
        migrations.AddField(
            model_name='requests',
            name='source',
            field=models.CharField(default='', help_text='Where this request call was obtained from', max_length=40),
            preserve_default=False,
        ),
    ]
