# Generated by Django 2.1.1 on 2018-09-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0010_auto_20180926_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='location',
            field=models.CharField(blank=True, help_text='Location name', max_length=60),
        ),
        migrations.AlterField(
            model_name='requests',
            name='name',
            field=models.CharField(blank=True, help_text='Name of requestee', max_length=50),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(blank=True, help_text='Status of request', max_length=15),
        ),
    ]
