# Generated by Django 2.1.1 on 2018-09-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0011_auto_20180926_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='need_water',
            field=models.BooleanField(default=False),
        ),
    ]
