# Generated by Django 2.1.2 on 2019-10-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0013_auto_20181101_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='request',
            field=models.ForeignKey(db_column='request', default='', help_text='The request to which this comment is made', on_delete=django.db.models.deletion.CASCADE, to='help.Requests'),
            preserve_default=False,
        ),
    ]
