# Generated by Django 2.1.1 on 2018-09-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
