# Generated by Django 2.1.1 on 2018-09-22 10:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('help', '0008_auto_20180922_1033'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('accounts', '0002_users_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
