# Generated by Django 2.1.1 on 2018-09-14 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(help_text='Unique ID of the camp', primary_key=True, serialize=False)),
                ('lat', models.CharField(help_text='Latitude', max_length=20)),
                ('lng', models.CharField(help_text='Longitude', max_length=20)),
                ('location', models.CharField(help_text='Location name', max_length=60)),
                ('capacity', models.IntegerField(help_text='The max capacity of the camp')),
                ('number_of_people', models.IntegerField(default=0, help_text='The number of people currently in the camp')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
