# Generated by Django 2.1.1 on 2018-09-26 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='admin',
        ),
        migrations.AddField(
            model_name='camp',
            name='user',
            field=models.ForeignKey(db_column='user', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
