# Generated by Django 2.1.2 on 2018-10-19 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camps', '0002_auto_20180926_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camp',
            new_name='Camps',
        ),
    ]
