# Generated by Django 2.1.2 on 2018-10-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0003_auto_20181019_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='camps',
            name='incharge',
            field=models.CharField(default='Suraj', help_text='Camp incharge', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camps',
            name='phone',
            field=models.CharField(default='0000000000', help_text='Camp phone number', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camps',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='camps/%Y/%m/%d/'),
        ),
    ]
