# Generated by Django 2.1.2 on 2018-10-23 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0004_auto_20181019_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampInhabitants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of person', max_length=100)),
                ('location', models.CharField(help_text='Original place of person', max_length=100)),
                ('blood_group', models.CharField(help_text='Blood group of person', max_length=5)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.Camps')),
            ],
        ),
    ]
