# Generated by Django 2.1.2 on 2018-10-24 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0005_campinhabitants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campinhabitants',
            name='camp',
            field=models.ForeignKey(db_column='camp', on_delete=django.db.models.deletion.CASCADE, to='camps.Camps'),
        ),
    ]
