# Generated by Django 2.1.2 on 2018-10-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectioncentres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCentreStock',
            fields=[
                ('id', models.AutoField(help_text='Unique ID of the stock', primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=30)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectioncentres.CollectionCentre')),
            ],
        ),
    ]
