# Generated by Django 2.1.2 on 2018-10-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectioncentres', '0002_collectioncentrestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncentrestock',
            name='need_quantity',
            field=models.IntegerField(default=0, help_text='Quantity required'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectioncentrestock',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Quantity in stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectioncentrestock',
            name='unit',
            field=models.CharField(default='', help_text='Unit of quantity', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectioncentrestock',
            name='item',
            field=models.CharField(help_text='Stock item', max_length=30),
        ),
    ]
