# Generated by Django 2.1.2 on 2018-10-16 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collectioncentres', '0003_auto_20181016_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncentrestock',
            name='user',
            field=models.ForeignKey(db_column='user', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
